# Generated by Django 3.1 on 2023-05-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210321_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('gpt', models.CharField(max_length=17000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
