# Generated by Django 3.1 on 2023-05-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
